INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Potter', '18');
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Germiona', '18');
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Volan de Mort', '103');
INSERT INTO `test`.`User` (`name`, `age`, `isAdmin`) VALUES ('Severus', '52', true);
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Draco', '19');
INSERT INTO `test`.`User` (`name`, `age`, `isAdmin`) VALUES ('Rubeus', '153', true);
INSERT INTO `test`.`User` (`name`, `age`, `isAdmin`) VALUES ('Albus', '204',true);
INSERT INTO `test`.`User` (`name`, `age`, `isAdmin`) VALUES ('Sirius', '48', true);
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Uizzley', '18');
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Rimus', '19');
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Nevill', '18');
INSERT INTO `test`.`User` (`name`, `age`, `isAdmin`) VALUES ('Minevra', '124', true);
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Dolores', '23');
INSERT INTO `test`.`User` (`name`, `age`, `isAdmin`) VALUES ('Lucius', '58', true);
INSERT INTO `test`.`User` (`name`, `age`) VALUES ('Vinki', '70');
